import { useState, useEffect, useRef } from 'react';
import Editor from '@monaco-editor/react';
import { Code2, Eye, Save, Copy, Download, RefreshCw } from 'lucide-react';
import { useBuilderStore } from '@/store/builderStore';

interface ProfessionalCodeEditorProps {
  onSave?: (code: any) => void;
}

function generateHTML(config: any): string {
  const { theme, sections, metadata } = config;
  const sorted = [...(sections || [])].sort((a: any, b: any) => a.order - b.order);

  let sectionsHTML = '';
  for (const section of sorted) {
    const p = section.props || {};
    const heading = p.heading || p.title || '';
    const subheading = p.subheading || p.subtitle || p.description || '';
    const bg = p.backgroundColor || '#ffffff';
    const text = p.textColor || '#1f2937';

    switch (section.type) {
      case 'HeroSection':
        sectionsHTML += `  <section class="hero" style="background:${bg};color:${text};background-image:url('${p.backgroundImage || ''}');background-size:cover;background-position:center;">
    <div class="hero-overlay"></div>
    <div class="hero-content">
      <h1>${heading}</h1>
      <p>${subheading}</p>
      ${p.ctaText ? `<a href="${p.ctaLink || '#'}" class="btn-primary">${p.ctaText}</a>` : ''}
    </div>
  </section>\n`;
        break;
      case 'AboutSection':
        sectionsHTML += `  <section class="about" style="background:${bg};color:${text};">
    <div class="container">
      <div class="about-grid">
        <div class="about-text">
          <h2>${heading}</h2>
          <p>${subheading}</p>
          <p>${p.description || ''}</p>
        </div>
        ${p.image ? `<div class="about-image"><img src="${p.image}" alt="${heading}" /></div>` : ''}
      </div>
    </div>
  </section>\n`;
        break;
      case 'FooterSection':
        sectionsHTML += `  <footer style="background:${bg || '#1f2937'};color:${text || '#ffffff'};">
    <div class="container">
      <h3>${p.businessName || p.companyName || ''}</h3>
      <p>${p.tagline || p.description || ''}</p>
      <p>${p.email || ''} | ${p.phone || ''}</p>
      <p>${p.address || ''}</p>
    </div>
  </footer>\n`;
        break;
      default:
        // Generic section
        const items = p.services || p.features || p.cards || p.categories || p.testimonials || p.offers || p.stats || p.faqs || [];
        sectionsHTML += `  <section class="section-${section.type.replace('Section', '').toLowerCase()}" style="background:${bg};color:${text};">
    <div class="container">
      <h2>${heading}</h2>
      <p class="section-subtitle">${subheading}</p>
      ${Array.isArray(items) ? `<div class="grid">${items.map((item: any) => `
        <div class="card">
          ${item.image ? `<img src="${item.image}" alt="${item.title || item.name || ''}" />` : ''}
          ${item.icon ? `<span class="icon">${item.icon}</span>` : ''}
          <h3>${item.title || item.name || item.question || ''}</h3>
          <p>${item.description || item.content || item.answer || item.price || ''}</p>
        </div>`).join('')}
      </div>` : ''}
    </div>
  </section>\n`;
    }
  }

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${metadata?.projectName || 'Website'}</title>
  <link href="https://fonts.googleapis.com/css2?family=${(theme?.fontFamily || 'Inter').replace(' ', '+')}&display=swap" rel="stylesheet" />
  <link rel="stylesheet" href="styles.css" />
</head>
<body>
${sectionsHTML}
  <script src="script.js"><\/script>
</body>
</html>`;
}

function generateCSS(config: any): string {
  const { theme } = config;
  const primary = theme?.primaryColor || '#3B82F6';
  const secondary = theme?.secondaryColor || '#1E40AF';
  const accent = theme?.accentColor || '#F59E0B';
  const font = theme?.fontFamily || 'Inter';

  return `/* Generated by ZeroBuild */
:root {
  --primary: ${primary};
  --secondary: ${secondary};
  --accent: ${accent};
  --font: '${font}', sans-serif;
}

* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: var(--font); line-height: 1.6; color: #1f2937; }

.container { max-width: 1200px; margin: 0 auto; padding: 0 1.5rem; }

/* Hero */
.hero { position: relative; min-height: 80vh; display: flex; align-items: center; justify-content: center; text-align: center; }
.hero-overlay { position: absolute; inset: 0; background: rgba(0,0,0,0.5); }
.hero-content { position: relative; z-index: 1; padding: 2rem; }
.hero h1 { font-size: clamp(2rem, 5vw, 4rem); font-weight: 700; margin-bottom: 1rem; color: #fff; }
.hero p { font-size: clamp(1rem, 2vw, 1.25rem); color: rgba(255,255,255,0.9); margin-bottom: 2rem; max-width: 600px; margin-inline: auto; }

/* Buttons */
.btn-primary { display: inline-block; padding: 0.75rem 2rem; background: var(--primary); color: #fff; text-decoration: none; border-radius: 0.5rem; font-weight: 600; transition: transform 0.2s, opacity 0.2s; }
.btn-primary:hover { opacity: 0.9; transform: translateY(-2px); }

/* Sections */
section { padding: 4rem 1.5rem; }
section h2 { font-size: clamp(1.5rem, 3vw, 2.5rem); font-weight: 700; text-align: center; margin-bottom: 0.5rem; }
.section-subtitle { text-align: center; color: #6b7280; margin-bottom: 3rem; font-size: 1.1rem; }

/* Grid */
.grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 1.5rem; }

/* Cards */
.card { background: #fff; border-radius: 1rem; padding: 1.5rem; box-shadow: 0 4px 20px rgba(0,0,0,0.08); transition: transform 0.2s; }
.card:hover { transform: translateY(-4px); }
.card img { width: 100%; height: 200px; object-fit: cover; border-radius: 0.75rem; margin-bottom: 1rem; }
.card .icon { font-size: 2.5rem; display: block; margin-bottom: 1rem; }
.card h3 { font-size: 1.2rem; font-weight: 600; margin-bottom: 0.5rem; }
.card p { color: #6b7280; font-size: 0.95rem; }

/* About */
.about-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 3rem; align-items: center; }
.about-image img { width: 100%; border-radius: 1rem; }
.about-text h2 { font-size: 2rem; margin-bottom: 1rem; }
.about-text p { color: #4b5563; margin-bottom: 1rem; }

/* Footer */
footer { padding: 3rem 1.5rem; text-align: center; }
footer h3 { font-size: 1.5rem; margin-bottom: 0.5rem; }
footer p { opacity: 0.8; margin-bottom: 0.5rem; }

/* Responsive */
@media (max-width: 768px) {
  .about-grid { grid-template-columns: 1fr; }
  .grid { grid-template-columns: 1fr; }
  section { padding: 3rem 1rem; }
}`;
}

function generateJS(): string {
  return `// Generated by ZeroBuild
document.addEventListener('DOMContentLoaded', () => {
  // Smooth scroll for anchor links
  document.querySelectorAll('a[href^="#"]').forEach(link => {
    link.addEventListener('click', (e) => {
      e.preventDefault();
      const target = document.querySelector(link.getAttribute('href'));
      if (target) target.scrollIntoView({ behavior: 'smooth' });
    });
  });

  // Scroll reveal animation
  const observer = new IntersectionObserver((entries) => {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        entry.target.style.opacity = '1';
        entry.target.style.transform = 'translateY(0)';
      }
    });
  }, { threshold: 0.1 });

  document.querySelectorAll('section, .card').forEach(el => {
    el.style.opacity = '0';
    el.style.transform = 'translateY(20px)';
    el.style.transition = 'opacity 0.6s ease, transform 0.6s ease';
    observer.observe(el);
  });
});`;
}

export const ProfessionalCodeEditor: React.FC<ProfessionalCodeEditorProps> = ({ onSave }) => {
  const { config } = useBuilderStore();
  const [activeTab, setActiveTab] = useState<'html' | 'css' | 'js'>('html');
  const [showPreview, setShowPreview] = useState(false);
  const [htmlCode, setHtmlCode] = useState('');
  const [cssCode, setCssCode] = useState('');
  const [jsCode, setJsCode] = useState('');
  const iframeRef = useRef<HTMLIFrameElement>(null);

  // Regenerate code when config changes
  useEffect(() => {
    setHtmlCode(generateHTML(config));
    setCssCode(generateCSS(config));
    setJsCode(generateJS());
  }, [config]);

  const getPreviewDoc = () => {
    return `<!DOCTYPE html><html><head><style>${cssCode}</style></head><body>${htmlCode.replace(/<!DOCTYPE[\s\S]*?<body>/, '').replace(/<\/body>[\s\S]*/, '').replace(/<link[^>]*styles\.css[^>]*>/, '').replace(/<script[^>]*script\.js[^>]*><\/script>/, '')}</body><script>${jsCode}<\/script></html>`;
  };

  const refreshPreview = () => {
    if (iframeRef.current) {
      iframeRef.current.srcdoc = getPreviewDoc();
    }
  };

  useEffect(() => { if (showPreview) refreshPreview(); }, [showPreview, htmlCode, cssCode, jsCode]);

  const handleCopy = () => {
    const code = activeTab === 'html' ? htmlCode : activeTab === 'css' ? cssCode : jsCode;
    navigator.clipboard.writeText(code);
  };

  const handleDownload = () => {
    const files = [
      { name: 'index.html', content: htmlCode },
      { name: 'styles.css', content: cssCode },
      { name: 'script.js', content: jsCode },
    ];
    files.forEach(f => {
      const blob = new Blob([f.content], { type: 'text/plain' });
      const a = document.createElement('a');
      a.href = URL.createObjectURL(blob);
      a.download = f.name;
      a.click();
    });
  };

  const currentCode = activeTab === 'html' ? htmlCode : activeTab === 'css' ? cssCode : jsCode;
  const setCurrentCode = activeTab === 'html' ? setHtmlCode : activeTab === 'css' ? setCssCode : setJsCode;

  return (
    <div className="flex-1 flex h-full bg-[#1e1e1e]">
      {/* Code Panel */}
      <div className={`flex flex-col ${showPreview ? 'w-1/2' : 'w-full'}`}>
        {/* Tabs + Actions */}
        <div className="flex items-center justify-between px-2 py-1.5 bg-[#252526] border-b border-[#333]">
          <div className="flex items-center gap-0.5">
            {(['html', 'css', 'js'] as const).map(tab => (
              <button key={tab} onClick={() => setActiveTab(tab)}
                className={`px-3 py-1.5 text-xs font-medium rounded transition-colors ${activeTab === tab ? 'bg-[#1e1e1e] text-white' : 'text-gray-400 hover:text-white'}`}>
                {tab === 'html' ? 'index.html' : tab === 'css' ? 'styles.css' : 'script.js'}
              </button>
            ))}
          </div>
          <div className="flex items-center gap-1">
            <button onClick={() => setShowPreview(!showPreview)} className={`p-1.5 rounded text-xs transition-colors ${showPreview ? 'bg-blue-600 text-white' : 'text-gray-400 hover:text-white hover:bg-white/10'}`} title="Toggle Preview">
              <Eye className="w-3.5 h-3.5" />
            </button>
            <button onClick={handleCopy} className="p-1.5 rounded text-gray-400 hover:text-white hover:bg-white/10" title="Copy"><Copy className="w-3.5 h-3.5" /></button>
            <button onClick={handleDownload} className="p-1.5 rounded text-gray-400 hover:text-white hover:bg-white/10" title="Download All"><Download className="w-3.5 h-3.5" /></button>
          </div>
        </div>

        {/* Monaco Editor */}
        <div className="flex-1 min-h-0">
          <Editor
            height="100%"
            language={activeTab === 'html' ? 'html' : activeTab === 'css' ? 'css' : 'javascript'}
            theme="vs-dark"
            value={currentCode}
            onChange={(v) => setCurrentCode(v || '')}
            options={{ fontSize: 13, minimap: { enabled: false }, wordWrap: 'on', scrollBeyondLastLine: false, automaticLayout: true, tabSize: 2 }}
          />
        </div>
      </div>

      {/* Live Preview */}
      {showPreview && (
        <div className="w-1/2 flex flex-col border-l border-[#333]">
          <div className="flex items-center justify-between px-3 py-1.5 bg-[#252526] border-b border-[#333]">
            <span className="text-xs text-gray-400">Live Preview</span>
            <button onClick={refreshPreview} className="p-1 rounded text-gray-400 hover:text-white hover:bg-white/10"><RefreshCw className="w-3.5 h-3.5" /></button>
          </div>
          <div className="flex-1 bg-white">
            <iframe ref={iframeRef} srcDoc={getPreviewDoc()} className="w-full h-full border-0" title="Preview" sandbox="allow-scripts" />
          </div>
        </div>
      )}
    </div>
  );
};
