import type { ComponentDefinition } from '@/types/component.types';

export const componentDefinitions: ComponentDefinition[] = [
  {
    type: 'HeroSection',
    label: 'Hero Section',
    icon: '🎯',
    category: 'hero',
    description: 'Full-screen hero section with heading, subheading, and CTA',
    defaultProps: {
      heading: 'Welcome to Our Business',
      subheading: 'We provide exceptional services for your needs',
      ctaText: 'Contact Us',
      ctaLink: '',
      backgroundImage: 'https://images.unsplash.com/photo-1557804506-669a67965ba0',
      backgroundColor: '#1F2937',
      textColor: '#FFFFFF',
      overlayOpacity: 0.5,
    },
  },
  {
    type: 'AboutSection',
    label: 'About Section',
    icon: '📖',
    category: 'content',
    description: 'Tell your story with text and image',
    defaultProps: {
      heading: 'About Us',
      description:
        'We are passionate about delivering excellence. Our team is dedicated to providing the best service possible.',
      image: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c',
      imagePosition: 'right' as const,
      backgroundColor: '#FFFFFF',
    },
  },
  {
    type: 'ServicesSection',
    label: 'Services Section',
    icon: '⚙️',
    category: 'content',
    description: 'Showcase your services with icons and descriptions',
    defaultProps: {
      heading: 'Our Services',
      subheading: 'What we offer',
      services: [
        {
          id: '1',
          icon: '🚀',
          title: 'Service One',
          description: 'Description of your first service',
        },
        {
          id: '2',
          icon: '💼',
          title: 'Service Two',
          description: 'Description of your second service',
        },
        {
          id: '3',
          icon: '🎨',
          title: 'Service Three',
          description: 'Description of your third service',
        },
      ],
      backgroundColor: '#F9FAFB',
      columns: 3 as const,
    },
  },
  {
    type: 'MenuSection',
    label: 'Menu Section',
    icon: '🍽️',
    category: 'content',
    description: 'Display menu items with categories',
    defaultProps: {
      heading: 'Our Menu',
      subheading: 'Delicious offerings',
      menuItems: [
        {
          id: '1',
          name: 'Item 1',
          description: 'Delicious menu item',
          price: '$12.99',
          image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c',
          category: 'Main',
        },
        {
          id: '2',
          name: 'Item 2',
          description: 'Another tasty option',
          price: '$14.99',
          image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445',
          category: 'Main',
        },
      ],
      categories: ['Main', 'Desserts', 'Drinks'],
      backgroundColor: '#FFFFFF',
    },
  },
  {
    type: 'GallerySection',
    label: 'Gallery Section',
    icon: '🖼️',
    category: 'content',
    description: 'Photo gallery with multiple layouts',
    defaultProps: {
      heading: 'Gallery',
      subheading: 'Our work in pictures',
      images: [
        {
          id: '1',
          url: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b',
          alt: 'Gallery image 1',
        },
        {
          id: '2',
          url: 'https://images.unsplash.com/photo-1511578314322-379afb476865',
          alt: 'Gallery image 2',
        },
        {
          id: '3',
          url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4',
          alt: 'Gallery image 3',
        },
      ],
      layout: 'grid' as const,
      backgroundColor: '#F9FAFB',
      columns: 3 as const,
    },
  },
  {
    type: 'TestimonialsSection',
    label: 'Testimonials Section',
    icon: '⭐',
    category: 'interactive',
    description: 'Customer reviews and testimonials',
    defaultProps: {
      heading: 'What Our Clients Say',
      subheading: 'Testimonials',
      testimonials: [
        {
          id: '1',
          name: 'John Doe',
          photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e',
          rating: 5,
          review: 'Excellent service! Highly recommended.',
          position: 'CEO, Company Inc',
        },
        {
          id: '2',
          name: 'Jane Smith',
          photo: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80',
          rating: 5,
          review: 'Amazing experience from start to finish.',
          position: 'Marketing Director',
        },
      ],
      backgroundColor: '#FFFFFF',
      layout: 'grid' as const,
    },
  },
  {
    type: 'OffersSection',
    label: 'Offers Section',
    icon: '🎁',
    category: 'content',
    description: 'Special offers and promotions',
    defaultProps: {
      heading: 'Special Offers',
      subheading: 'Limited time deals',
      offers: [
        {
          id: '1',
          title: 'Summer Special',
          description: 'Get 20% off on all services',
          image: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da',
          discount: '20% OFF',
          validUntil: '2025-12-31',
        },
      ],
      backgroundColor: '#F9FAFB',
    },
  },
  {
    type: 'CTASection',
    label: 'Call to Action',
    icon: '📞',
    category: 'interactive',
    description: 'Strong call-to-action section',
    defaultProps: {
      heading: 'Ready to Get Started?',
      description: 'Contact us today and let\'s make something amazing together!',
      ctaText: 'Get in Touch',
      ctaLink: '',
      backgroundImage: '',
      backgroundColor: '#3B82F6',
      textColor: '#FFFFFF',
    },
  },
  {
    type: 'FooterSection',
    label: 'Footer Section',
    icon: '📄',
    category: 'footer',
    description: 'Footer with business info and social links',
    defaultProps: {
      businessName: 'Your Business',
      tagline: 'Excellence in every service',
      address: '123 Main St, City, State 12345',
      phone: '+1 (234) 567-8900',
      email: 'info@yourbusiness.com',
      socialLinks: [
        {
          id: '1',
          platform: 'Facebook',
          url: 'https://facebook.com',
          icon: '📘',
        },
        {
          id: '2',
          platform: 'Instagram',
          url: 'https://instagram.com',
          icon: '📷',
        },
        {
          id: '3',
          platform: 'Twitter',
          url: 'https://twitter.com',
          icon: '🐦',
        },
      ],
      backgroundColor: '#1F2937',
      textColor: '#FFFFFF',
    },
  },
  // Note: FloatingWhatsApp is controlled via WhatsApp settings, not as a draggable component

  // Advanced Modern Components
  {
    type: 'CardSection',
    label: 'Card Section',
    icon: '🎴',
    category: 'content',
    description: 'Modern card layout with glassmorphism and advanced styles',
    defaultProps: {
      heading: 'Popular Courses',
      subheading: 'Explore our featured content',
      cards: [
        {
          id: '1',
          image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3',
          title: 'Digital Marketing',
          description: 'Learn the fundamentals of modern digital marketing',
          badge: 'Best Seller',
          badgeColor: '#F59E0B',
          rating: 4.8,
          price: '$49.99',
          tags: ['Marketing', 'Business'],
        },
        {
          id: '2',
          image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085',
          title: 'Web Development',
          description: 'Master full-stack web development from scratch',
          badge: 'New',
          badgeColor: '#10B981',
          rating: 4.9,
          price: '$79.99',
          tags: ['Programming', 'Web'],
        },
        {
          id: '3',
          image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5',
          title: 'UI/UX Design',
          description: 'Create beautiful and intuitive user experiences',
          badge: 'Popular',
          badgeColor: '#8B5CF6',
          rating: 4.7,
          price: '$59.99',
          tags: ['Design', 'Creative'],
        },
      ],
      backgroundColor: '#FFFFFF',
      columns: 3,
      cardLayout: 'vertical',
      cardStyle: 'elevated',
      borderRadius: 'xl',
      shadowSize: 'lg',
      hoverEffect: 'lift',
      scrollAnimation: 'slide-up',
      staggerDelay: 100,
      colorScheme: 'warm',
      spacing: 'normal',
    },
  },
  {
    type: 'StatsSection',
    label: 'Stats Section',
    icon: '📊',
    category: 'content',
    description: 'Animated counter statistics with modern design',
    defaultProps: {
      heading: 'Our Impact',
      subheading: 'Numbers that speak for themselves',
      stats: [
        {
          id: '1',
          value: '12000',
          label: 'Happy Customers',
          icon: '👥',
          suffix: '+',
          animateCounter: true,
        },
        {
          id: '2',
          value: '9',
          label: 'Years Experience',
          icon: '⭐',
          suffix: '+',
          animateCounter: true,
        },
        {
          id: '3',
          value: '358',
          label: 'Courses Available',
          icon: '📚',
          suffix: '+',
          animateCounter: true,
        },
        {
          id: '4',
          value: '47',
          label: 'Award Winners',
          icon: '🏆',
          suffix: '+',
          animateCounter: true,
        },
      ],
      backgroundColor: '#F9FAFB',
      columns: 4,
      cardStyle: 'glass',
      borderRadius: 'xl',
      scrollAnimation: 'zoom',
      staggerDelay: 100,
      colorScheme: 'professional',
      spacing: 'relaxed',
    },
  },
  {
    type: 'CategorySection',
    label: 'Category Pills',
    icon: '🏷️',
    category: 'interactive',
    description: 'Interactive category filters with pills, cards or buttons',
    defaultProps: {
      heading: 'Top Categories',
      subheading: 'Browse by topic',
      categories: [
        {
          id: '1',
          label: 'Academic',
          icon: '📚',
          count: 120,
          color: '#8B5CF6',
        },
        {
          id: '2',
          label: 'Technical',
          icon: '💻',
          count: 85,
          color: '#3B82F6',
        },
        {
          id: '3',
          label: 'Vocational',
          icon: '🔧',
          count: 95,
          color: '#F59E0B',
        },
        {
          id: '4',
          label: 'Others',
          icon: '✨',
          count: 45,
          color: '#10B981',
        },
      ],
      backgroundColor: '#FFFFFF',
      layout: 'pills',
      allowMultiSelect: false,
      borderRadius: 'full',
      scrollAnimation: 'slide-up',
      staggerDelay: 50,
      colorScheme: 'vibrant',
      spacing: 'normal',
    },
  },
  {
    type: 'ProfileSection',
    label: 'Profile Cards',
    icon: '👤',
    category: 'content',
    description: 'Team or mentor profile cards with ratings',
    defaultProps: {
      heading: 'Meet Our Mentors',
      subheading: 'Learn from the best',
      profiles: [
        {
          id: '1',
          name: 'Ronald Richards',
          photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e',
          role: 'Senior Developer',
          bio: 'Expert in React and Node.js with 10+ years of experience',
          rating: 4.9,
          reviews: 1243,
        },
        {
          id: '2',
          name: 'Theresa Webb',
          photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330',
          role: 'UI/UX Designer',
          bio: 'Passionate about creating beautiful user experiences',
          rating: 4.8,
          reviews: 982,
        },
        {
          id: '3',
          name: 'Leslie Alexander',
          photo: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80',
          role: 'Marketing Expert',
          bio: 'Helping businesses grow through strategic marketing',
          rating: 5.0,
          reviews: 1567,
        },
      ],
      backgroundColor: '#FFFFFF',
      columns: 3,
      showRating: true,
      showSocial: false,
      cardStyle: 'elevated',
      borderRadius: '2xl',
      shadowSize: 'lg',
      hoverEffect: 'lift',
      scrollAnimation: 'fade',
      staggerDelay: 100,
      colorScheme: 'professional',
      spacing: 'normal',
    },
  },
  {
    type: 'PricingSection',
    label: 'Pricing Tables',
    icon: '💰',
    category: 'content',
    description: 'Modern pricing tables with billing toggle',
    defaultProps: {
      heading: 'Choose Your Plan',
      subheading: 'Flexible pricing for everyone',
      plans: [
        {
          id: '1',
          name: 'Basic',
          price: '$29',
          period: '/month',
          description: 'Perfect for getting started',
          features: [
            '5 Projects',
            '10 GB Storage',
            'Email Support',
            'Basic Analytics',
          ],
          recommended: false,
          ctaText: 'Get Started',
        },
        {
          id: '2',
          name: 'Professional',
          price: '$79',
          period: '/month',
          description: 'Best for growing teams',
          features: [
            'Unlimited Projects',
            '100 GB Storage',
            'Priority Support',
            'Advanced Analytics',
            'Custom Domain',
          ],
          recommended: true,
          ctaText: 'Get Started',
        },
        {
          id: '3',
          name: 'Enterprise',
          price: '$199',
          period: '/month',
          description: 'For large organizations',
          features: [
            'Everything in Pro',
            'Unlimited Storage',
            'Dedicated Support',
            'Custom Integration',
            'SLA Guarantee',
          ],
          recommended: false,
          ctaText: 'Contact Sales',
        },
      ],
      backgroundColor: '#FFFFFF',
      billingToggle: true,
      cardStyle: 'elevated',
      borderRadius: 'xl',
      shadowSize: 'lg',
      hoverEffect: 'lift',
      scrollAnimation: 'slide-up',
      staggerDelay: 150,
      buttonStyle: 'solid',
      buttonSize: 'lg',
      colorScheme: 'professional',
      spacing: 'relaxed',
    },
  },
  {
    type: 'FAQSection',
    label: 'FAQ Section',
    icon: '❓',
    category: 'content',
    description: 'Frequently asked questions with accordion or grid layout',
    defaultProps: {
      heading: 'Frequently Asked Questions',
      subheading: 'Find answers to common questions',
      faqs: [
        {
          id: '1',
          question: 'How do I get started?',
          answer: 'Simply sign up for an account and you can start using our platform immediately. No credit card required for the trial period.',
        },
        {
          id: '2',
          question: 'What payment methods do you accept?',
          answer: 'We accept all major credit cards, PayPal, and bank transfers for enterprise plans.',
        },
        {
          id: '3',
          question: 'Can I cancel my subscription anytime?',
          answer: 'Yes, you can cancel your subscription at any time. No questions asked, and no cancellation fees.',
        },
        {
          id: '4',
          question: 'Do you offer refunds?',
          answer: 'We offer a 30-day money-back guarantee on all our plans. If you are not satisfied, contact us for a full refund.',
        },
      ],
      backgroundColor: '#FFFFFF',
      layout: 'accordion',
      cardStyle: 'elevated',
      borderRadius: 'lg',
      scrollAnimation: 'slide-up',
      staggerDelay: 100,
      colorScheme: 'professional',
      spacing: 'normal',
    },
  },
  {
    type: 'TimelineSection',
    label: 'Timeline',
    icon: '📅',
    category: 'content',
    description: 'Visual timeline for history or process',
    defaultProps: {
      heading: 'Our Journey',
      subheading: 'Building the future, one step at a time',
      items: [
        {
          id: '1',
          year: '2018',
          title: 'Company Founded',
          description: 'Started with a vision to revolutionize the industry',
          icon: '🚀',
        },
        {
          id: '2',
          year: '2019',
          title: 'First Product Launch',
          description: 'Released our flagship product to market',
          icon: '🎯',
        },
        {
          id: '3',
          year: '2021',
          title: 'Reached 10K Users',
          description: 'Milestone achievement in user growth',
          icon: '🎉',
        },
        {
          id: '4',
          year: '2023',
          title: 'Global Expansion',
          description: 'Expanded operations to 15 countries',
          icon: '🌍',
        },
      ],
      backgroundColor: '#FFFFFF',
      orientation: 'vertical',
      cardStyle: 'elevated',
      borderRadius: 'lg',
      scrollAnimation: 'slide-up',
      staggerDelay: 150,
      colorScheme: 'professional',
      spacing: 'relaxed',
    },
  },
  {
    type: 'FeatureSection',
    label: 'Feature Grid',
    icon: '✨',
    category: 'content',
    description: 'Showcase features with icons and descriptions',
    defaultProps: {
      heading: 'Amazing Features',
      subheading: 'Everything you need to succeed',
      features: [
        {
          id: '1',
          icon: '⚡',
          title: 'Lightning Fast',
          description: 'Optimized performance for the best user experience',
        },
        {
          id: '2',
          icon: '🔒',
          title: 'Secure & Safe',
          description: 'Enterprise-grade security to protect your data',
        },
        {
          id: '3',
          icon: '📱',
          title: 'Mobile Ready',
          description: 'Fully responsive design that works on all devices',
        },
        {
          id: '4',
          icon: '🎨',
          title: 'Customizable',
          description: 'Tailor everything to match your brand',
        },
        {
          id: '5',
          icon: '💬',
          title: '24/7 Support',
          description: 'Always here to help whenever you need us',
        },
        {
          id: '6',
          icon: '🚀',
          title: 'Easy Integration',
          description: 'Seamlessly integrate with your existing tools',
        },
      ],
      backgroundColor: '#FFFFFF',
      columns: 3,
      iconStyle: 'circular',
      cardStyle: 'elevated',
      borderRadius: 'xl',
      shadowSize: 'md',
      hoverEffect: 'lift',
      scrollAnimation: 'zoom',
      staggerDelay: 100,
      colorScheme: 'vibrant',
      spacing: 'normal',
    },
  },
  {
    type: 'JobBoardSection',
    label: 'Job Board',
    icon: '💼',
    category: 'content',
    description: 'Complete job board with search, filters, and job listings',
    defaultProps: {
      heading: 'Find your Dream Job',
      subheading: 'Looking for jobs? Browse our latest job openings to view & apply oto the best jobs today',
      jobs: [
        {
          id: '1',
          title: 'Product Designer',
          company: 'Google',
          logo: 'https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=100&h=100&fit=crop',
          location: 'Seattle, WA,USA',
          jobType: 'full-time',
          workMode: 'remote',
          salary: '$80,000 - $120,000',
          description: 'We are seeking a talented Product Designer to join our growing design team and help shape the future of our digital products.',
          requirements: [
            "Bachelor's degree in Design or equivalent practical experience",
            'A portfolio that showcases refined digital product design across multiple projects',
          ],
          datePosted: '2025-12-14',
          tags: ['Design', 'UI/UX', 'Figma'],
        },
        {
          id: '2',
          title: 'UX Designer',
          company: 'Meta Facebook',
          logo: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?w=100&h=100&fit=crop',
          location: 'New York, NY,USA',
          jobType: 'full-time',
          workMode: 'hybrid',
          salary: '$90,000 - $140,000',
          description: 'Join our UX team to create intuitive and engaging user experiences that delight millions of users worldwide.',
          requirements: [
            "Bachelor's degree in Design or equivalent practical experience",
            '3+ years of experience in product design or UX design',
          ],
          datePosted: '2025-12-13',
          tags: ['UX', 'Research', 'Prototyping'],
        },
        {
          id: '3',
          title: 'Interaction Designer',
          company: 'Amazon',
          logo: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=100&h=100&fit=crop',
          location: 'Seattle, WA,USA',
          jobType: 'part-time',
          workMode: 'on-site',
          salary: '$50/hour',
          description: 'Design beautiful and intuitive interactions that bring our products to life. Work with cross-functional teams to deliver exceptional user experiences.',
          requirements: [
            'Strong portfolio demonstrating interaction design work',
            'Experience with motion design and prototyping tools',
          ],
          datePosted: '2025-12-10',
          tags: ['Interaction', 'Animation', 'Prototyping'],
        },
        {
          id: '4',
          title: 'Senior Product Designer',
          company: 'Apple',
          logo: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=100&h=100&fit=crop',
          location: 'San Francisco, CA,USA',
          jobType: 'full-time',
          workMode: 'remote',
          salary: '$120,000 - $180,000',
          description: 'Lead the design of our flagship products and mentor junior designers. Shape the future of user experience at Apple.',
          requirements: [
            '7+ years of experience in product design',
            'Strong leadership and mentorship skills',
            'Portfolio showcasing shipped products',
          ],
          datePosted: '2025-12-15',
          tags: ['Leadership', 'Product Design', 'iOS'],
        },
        {
          id: '5',
          title: 'UI/UX Designer',
          company: 'Microsoft',
          logo: 'https://images.unsplash.com/photo-1633409361618-c73427e4e206?w=100&h=100&fit=crop',
          location: 'Remote',
          jobType: 'freelance',
          workMode: 'remote',
          salary: '$60-$100/hour',
          description: 'Design beautiful interfaces for our suite of productivity tools. Collaborate with product managers and engineers to deliver high-quality designs.',
          requirements: [
            'Strong UI design skills with attention to detail',
            'Experience designing for enterprise applications',
          ],
          datePosted: '2025-12-12',
          tags: ['UI Design', 'Enterprise', 'Figma'],
        },
      ],
      backgroundColor: '#F3F4F6',
      showFilters: true,
      showSearch: true,
      cardStyle: 'elevated',
      borderRadius: 'lg',
      shadowSize: 'md',
      scrollAnimation: 'fade',
      staggerDelay: 100,
      colorScheme: 'professional',
      spacing: 'normal',
      buttonStyle: 'solid',
      buttonSize: 'md',
    },
  },
];

export function getComponentDefinition(type: string): ComponentDefinition | undefined {
  return componentDefinitions.find((def) => def.type === type);
}

export function getDefaultProps(type: string): any {
  const definition = getComponentDefinition(type);
  return definition?.defaultProps || {};
}
